---
title: "Draft Report"
author: "203 Section 6, Team 1"
output: pdf_document
---

### 1. An Introduction

**Research Question:** How is the COVID case rate related to the population density and distribution of demographics of a state? How does the effect of population make-up on case rate compare with the effect of policy decisions made in each state?"

For this report, the investigation will be centered around the effect of population metrics such as density and demographics and policy on the COVID case rates across the United States (US), which is grouped by the 50 states plus the District of Columbia (D.C.). This research question aims to measure the case rate per 100,000 residents within each state based on the make-up of the population, as well as the policy decisions that were or were not put into place in order to combat the rise of COVID cases. In this sense, the aim is to measure how dependent the COVID case rate is on that of which cannot be controlled (i.e., population and demographics) vs that of which can be controlled to a certain degree (i.e., implementation of policies to attempt to combat cases). With this information, one could suggest whether or not the proliferation of COVID can be controlled, and to the level at which these policies help with this control.

This question can be broken up into two distinctive areas of investigation. The first and primary area of investigation involves how the COVID case rate is affected by population metrics. For this, the key variables are COVID case rate per 100,000 residents and the population density per square mile. This will provide an initial understanding in the relationship between the spread of the virus and how densely populated a state is. Following this, the analysis considers variables that address the make-up of these populations, specifically focusing on the distribution of demographics such as race/ethnicity and age. In order to account for the varying population sizes across the states, the variables are operationalized by specifically looking at variables that contain a rate, in order to standardize across the samples. In this sense, the analysis quantifies the spread of COVID by leveraging the COVID case rate per 100,000 rate, and for population demographics it investigates the percentage distribution of the race/ethnicity and age categories (e.g., White % of Total Population).

The secondary area of investigation will be to also include variables that measure policy implementation within states, and to compare the effect of these as opposed to the primary area of investigation that is population metrics. Specifically, there is a focus on policies that address the mandates of wearing masks within the state. Through this, the aim is to analyze whether the implementation of mask related policies will have an effect on case rate, as well as the degree of this effect relative to population metrics. To operationalize these policies and simplifying the measurements, the models will only consider whether or not these policies were implemented through indicator variables (1 = implemented, 0 = not implemented).

Prior to the analysis, it is important to identify a set of assumptions that have been made throughout the report and to assess the appropriateness of the data. Although there may be other considerations against the appropriateness of the data, the following highlights three particular arguments that must be taken into account when interpreting the results of the analysis.

Firstly, it is important to note that given each state (with the addition of the District of Columbia) is treated as a unique data point, the sample contains 51 data points. Although this size meets the general rule of an adequate sample size, as the analysis begins to factor in the wide range of potential population distributions and demographics within the states, it is clear that there is large variation within the sample. For example, the population density can have large variability depending on the population concentration among a few large areas as well as the level of uninhabited or sparsely inhabited land within a state, while the demographics of population can depend on a wide range of factors such as geographic location and employment opportunities. It is also important to note that these data points cannot be considered independent of each other, as there is a lot of interstate travel and regional similarities in terms of population and policy. This indicates that the sample cannot be assumed to be IID. 

Secondly, note that there are many internal and external aspects of the selected variables that have not been included within the models. Just addressing the internal information that is lost, it can be seen that much of the information is not captured given the methods of operationalization. Among others, the loss of date-related information within policy implementation variables strips out any contextual knowledge regarding the length of policy implementation, and precludes the identification of how long a specific policy was implemented. Assuming that policy implementation has some effect on case rate, this difference in length of time could play a large part in the effect. There are also other external aspects that cannot be included, such as the level of population density broken out among different population demographics. 

Finally, with regard to the policy variables, this report focuses solely on mask mandates. Given this, it does not capture the effect of other policies that may or may not have a greater effect on the case rate (e.g., implementation of stay-at-home orders). This follows for the population-related variables, as they capture race/ethnicity and poverty, but not other characteristics such as proportions of residents with pre-existing conditions. In justification, these choices were largely made due to there either being an appropriate amount of samples in each category (e.g., most states have implemented basic policies such as the closure of non-essential businesses and the implementation of stay-at-home orders, and thus these were not included given the lack of samples for the states that have not implemented them), or that data on other policies or demographic measures were simply not readily available in the dataset.

### 2. A Model Building Process

  The primary variable of interest will be the total covid case rate per 100,000 residents. The covid case rate was judged to give a better understanding than the death rate because of the potential for other, unrecorded variables that could be correlated with a person dying from covid versus just becoming infected. For example, the availability and quality of medical care in a state may impact its ability to keep covid infected patients alive, although this is not represented in the data set. The health status of the residents in one state compared to another state may also affect the death rate, but this is also not included. Instead, the covid infection rate was chosen so that these other variables which may correlate with the death rate would not have to be considered. Finally, the covid infection rate was also chosen on a per capita basis so that potential total population differences between states would already be accounted for in the variable. 
  
  The modeling goal for the covid case rate will be one of description. A modelf of causation may be created out of this model if potential causal relationships are examined and incorporated into the model's structure. This may later be expanded to predict the covid case rate in the past seven days in order for a state to use it to potentially judge what effect a modeled policy may have on its current situation. 
  
  There are two broad groups of covariates which will be examined in building the model. The first is demographic information on the state, such as population density, the unemployment rate, or rate of people living in poverty. The second general group is that of policy decisions taken by the state, such as mask mandates, legal enforcements of policies, or the political party of the state's governor (which is assumed to be related to the policies they may support). Problematic covariates would include any of the other direct measures of covid severity in the state, such as total infection rate not on a per capita basis or death rates. It can be assumed that these variables would be colinear with the primary variable of interest since more covid cases per capita would imply more total cases not adjusted for population or be strongly correlated with more deaths per capita, etc. 
